services:
  # üóÑÔ∏è Banco de dados
  db:
    image: postgres:16
    container_name: postgres-bus-system
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: ${TZ}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - bus_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ‚òï Quarkus
  app:
    build:
      context: ./core
      dockerfile: dev.Dockerfile
    container_name: quarkus-bus-system
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_EXTERNAL_PORT: ${DB_EXTERNAL_PORT}
      SERVER_EXTERNAL_PORT: ${SERVER_EXTERNAL_PORT}
      SERVER_DEBUG_PORT: ${SERVER_DEBUG_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_ADMIN_TOKEN: ${DB_ADMIN_TOKEN}
      TZ: ${TZ}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${SERVER_DEBUG_PORT}"
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_EXTERNAL_PORT}"
      - "${SERVER_DEBUG_PORT}:${SERVER_DEBUG_PORT}"

volumes:
  bus_pgdata:
  ollama_models:
